### ISSUE TITLE
Demo needs prefilled credentials

### ISSUE THREAD

**Issue by hornofj** [Einstore/EinstoreAdmin#36]
**Prerequisites:**
An anonymous user wants to see the demo so he goes to the login page of the demo installation.

**Current behaviour:**
He cannot log in because he does not know the credentials and there is no easy way to find them.

**Intended behaviour:**
The credentials are prefilled in the login/password fields and the user just clicks "Login".

**Comment by ViliamKopecky** [comment]
This should be provided by api in auth providers config.

**Comment by hornofj** [comment]
Light version of this feature: Before the user clicks on Demo link from the einstore homepage, an intermediate very simple html page (or popup) is displayed showing the credentials. This way, we do not need to modify einstore code and this can be implemented in the website only. That§s enough for now.
