### ISSUE TITLE
Invite allows to set invalid password

### ISSUE THREAD

**Issue by hornofj** [Einstore/EinstoreAdmin#39]
**Prerequisites:**
The user gets the invite and sets new password.

**Current behaviour:**
If the password is invalid for the login form, the user still can save such "invalid" password.

**Intended behaviour:**
If the password is invalid for the login form, the user should get a warning telling him how the password should look like so it can use it for login.

**Comment by rafiki270** [comment]
uf, thanks for this :( ... will fix ASAP

**Comment by ViliamKopecky** [comment]
Waiting for https://github.com/Einstore/EinstoreAdmin/issues/50 and then we will see.

**Comment by ViliamKopecky** [comment]
Also waiting for https://github.com/Einstore/Einstore/issues/95

**Comment by hornofj** [comment]
moved to Einstore/Einstore
https://github.com/Einstore/Einstore/issues/103
