### ISSUE TITLE
Search by tags

### ISSUE THREAD

**Issue by hornofj** [Einstore/EinstoreAdmin#42]
**Prerequisites:**
apps?tags=["lorem"] returns the app 048B269C-B3DB-41CC-BCEB-99AFD741FA8F
apps?tags=["ipsum-dolor"] returns the app 048B269C-B3DB-41CC-BCEB-99AFD741FA8F
apps?tags=["lorem","ipsum-dolor"] does and should do the following:

**Current behaviour:**
Returns no results.

**Intended behaviour:**
Should return both apps.

**Comment by rafiki270** [comment]
nope, tags are meant to be filters, not inclusive search criteria

**Comment by hornofj** [comment]
ok, makes sense
