### ISSUE TITLE
Add new team

### ISSUE THREAD

**Issue by hornofj** [Einstore/EinstoreAdmin#47]
team name and "Team Identifier" ("team-identifier")

team identifier should be generated from the team name but the user can override the suggested indentifier, the app needs to check if the identifier is unique

**Comment by rafiki270** [comment]
that's how it works?!

**Comment by hornofj** [comment]
the identifier should be prefilled onkeyup or on onblur when filling the team name in, now the identifier is not visible

**Comment by hornofj** [comment]
moved here https://github.com/Einstore/Einstore/issues/98
