### ISSUE TITLE
Adding empty tag

### ISSUE THREAD

**Issue by hornofj** [Einstore/EinstoreAdmin#55]
I can add one empty tag, when I try to add another empty tag, the UI does nothing.

The action should should block adding empty tags.

<img width="464" alt="Bildschirmfoto 2019-04-24 um 10 05 00" src="https://user-images.githubusercontent.com/2500352/56642869-b2992380-6678-11e9-823a-cdef06608d7e.png">

**Comment by rafiki270** [comment]
Backend should return an error on empty tag
